### ISSUE TITLE
Problemas prusaslicer y orcaslicer

### ISSUE THREAD

**Issue by mojamuto** [3dwork-io/3dwork-klipper#1]
He copiado y pegado el macro start_print, y he añadido lo siguiente a prusaslicer:

`M190 S0 ; Prevents prusaslicer from prepending m190 to the gcode ruining our macro
M109 S0 ; Prevents prusaslicer from prepending m109 to the gcode ruining our macro
SET_PRINT_STATS_INFO TOTAL_LAYER=[total_layer_count] ; Provide layer information
START_PRINT EXTRUDER_TEMP=[first_layer_temperature[initial_extruder]] BED_TEMP=[first_layer_bed_temperature] PRINT_MIN={first_layer_print_min[0]},{first_layer_print_min[1]} PRINT_MAX={first_layer_print_max[0]},{first_layer_print_max[1]}`

A la hora de imprimir  un archivo, la cama llega a la temperatura marcada y no hace nada mas.
Si borro las lineas:

`M190 S0 ; Prevents prusaslicer from prepending m190 to the gcode ruining our macro
M109 S0 ; Prevents prusaslicer from prepending m109 to the gcode ruining our macro`

Si que termina de imprimir.

Con orcaslicer tengo el mismo problema, calienta la cama hasta la temperatura objetivo pero no  hace nada mas, ni borrando las lineas:

`M190 S0 ; Prevents prusaslicer from prepending m190 to the gcode ruining our macro
M109 S0 ; Prevents prusaslicer from prepending m109 to the gcode ruining our macro`

consigo imprimir

**Comment by alienboyxp** [comment]
@mojamuto puedes pasar una captura? en todo caso si lo has puesto tal cual lo has pegado aqui me temo que deberias tener cuidado con el copy&paste :)
![image](https://github.com/3dwork-io/3dwork-klipper/assets/18049820/cdafa742-f4fc-446f-b9de-5619ffd3e39d)
En todas mis impresoras, y resto de compañero que lo utilizan y nadie ha reportado ningun problema, ademas que es algo que aconseja PrusaSlicer/OrcaSlicer con perfiles de terceros.
En cualquier caso te aconsejaria realizar estas consultas en nuestro grupo de Telegram https://t.me/Klipper_Firmware_ES/96023 ya que no es un problema en principio del script y revises bien la documentacion del bundle https://klipper.3dwork.io/klipper/mejoras/3dwork-klipper-bundle

**Comment by mojamuto** [comment]
Muchas gracias por contestar, acabo de entrar al grupo y lo comentare por alli.
Las capturas de pantalla

En prusa slicer le tengo borradas las lineas de M1909 y 109 para que funcione:
![Captura de pantalla_2024-03-14_18-27-01](https://github.com/3dwork-io/3dwork-klipper/assets/36079583/d7f5b345-15e0-4328-b343-fd334f6b3e2d)

En orcaslicer da igual si pongo las lineas de m190 y 109, siempre tengo este error:

![Captura de pantalla_2024-03-14_18-07-18](https://github.com/3dwork-io/3dwork-klipper/assets/36079583/65ceba2c-0c8a-4ee1-aa6c-13c54da1ae9e)
